# Generated by Django 3.0.1 on 2020-01-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200105_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='your_choice',
            field=models.BooleanField(default=False),
        ),
    ]
